before_script:
    - apt-get update -yqq
    - 'which ssh-agent || ( apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get install rsync -yqq --force-yes )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ruby -v
    - gem update --system
    - gem install bundler -v '~>1.11'
    - bundler --version

stages:
    - test
    - deploy
    - build

test_21:
    image: ruby:2.1
    stage: test
    only:
        - master
    script:
        - make
        - make test

test_22:
    image: ruby:2.2
    stage: test
    only:
        - master
    script:
        - make
        - make test

test_23:
    image: ruby:2.3
    stage: test
    only:
        - master
    script:
        - make
        - make test

deploy_cov:
    image: ruby:2.3
    stage: deploy
    only:
        - master
    script:
        - make
        - make cov
        - 'rsync ${RSYNC_OPTIONS} coverage ${RSYNC_USER}@${RSYNC_HOST}:${RSYNC_REMOTE_PATH}'

deploy_doc:
    image: ruby:2.3
    stage: deploy
    only:
        - master
    script:
        - make
        - make doc
        - 'rsync ${RSYNC_OPTIONS} doc ${RSYNC_USER}@${RSYNC_HOST}:${RSYNC_REMOTE_PATH}'

build_infos:
    image: ruby:2.3
    stage: build
    environment: production
    only:
        - master
    script:
        - 'printf "%s %s %s\n\ntermkit: %s (%s)\nid: %s\nref: %s@%s\nstage: %s\nserver: %s %s\n" $(date +"%F %T %z") $(ruby -I lib -rtermkit -e "puts %{#{TheFox::TermKit::VERSION} #{TheFox::TermKit::DATE}}") $CI_BUILD_ID $CI_BUILD_REF $CI_BUILD_REF_NAME $CI_BUILD_STAGE $CI_SERVER_NAME $CI_SERVER_VERSION > build.txt'
        - 'rsync ${RSYNC_OPTIONS} build.txt ${RSYNC_USER}@${RSYNC_HOST}:${RSYNC_REMOTE_PATH}'
