language: ruby
rvm:
    - 2.1
    - 2.2
sudo: required
before_install:
    - gem update --system
    - gem install bundler -v '~>1.11'
    - bundler --version
install:
    - make
    - gem build termkit.gemspec
    - gem install termkit-*.gem
    - gem list -l termkit
script:
    - make test
